# Generated by Django 5.1.6 on 2025-02-17 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nutrient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('kalories', models.PositiveIntegerField(default=0)),
                ('proteins', models.PositiveIntegerField(default=0)),
                ('fats', models.PositiveIntegerField(default=0)),
                ('carbohydrates', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='NutrientUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MealPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigner', to='user_profile.userprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profile.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('meal_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diet.mealplan')),
                ('nutrient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diet.nutrient')),
            ],
        ),
        migrations.AddField(
            model_name='nutrient',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diet.nutrientunit'),
        ),
        migrations.CreateModel(
            name='PromptLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('prompt', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meal_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diet.mealplan')),
            ],
        ),
    ]
