# Generated by Django 5.1.6 on 2025-04-18 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_remove_message_seen_message_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['created_at']},
        ),
        migrations.RenameField(
            model_name='message',
            old_name='type',
            new_name='message_type',
        ),
    ]
