# Generated by Django 5.1.6 on 2025-02-14 15:39

import django.db.models.deletion
import django_resized.forms
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('doctor', 'doctor'), ('patient', 'patient')], default='patient', max_length=10)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('photo', django_resized.forms.ResizedImageField(crop=['middle', 'center'], default='profiles/default.png', force_format='WEBP', keep_meta=True, quality=80, scale=None, size=[300, 300], upload_to='profiles')),
                ('is_verified', models.BooleanField(default=False)),
                ('full_address', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
