# Generated by Django 5.1.6 on 2025-05-14 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='asigned_patient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='user_profile.patient'),
            preserve_default=False,
        ),
    ]
