# Generated by Django 5.1.6 on 2025-06-03 13:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_notification_asigned_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='start_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
