# Generated by Django 5.1.6 on 2025-06-03 15:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_patient_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='valid_until',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notification',
            name='asigned_patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='user_profile.patient'),
        ),
    ]
