# Generated by Django 5.1.6 on 2025-06-03 18:31

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0005_notification_valid_until_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='photo',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], default='profiles/default.webp', force_format='WEBP', keep_meta=True, null=True, quality=80, scale=None, size=[300, 300], upload_to='profiles/'),
        ),
    ]
